### ISSUE TITLE
Support Node.js ESM

### ISSUE THREAD

**Issue by jaydenseric** [slicknode/graphql-query-complexity#65]
Node.js ESM is not supported; please support it.

In `demo.mjs`:

```js
import {
  createComplexityRule,
  simpleEstimator,
} from 'graphql-query-complexity';
```

Then run `node demo.mjs`:

```
file://[redacted]/demo.mjs:3
  simpleEstimator,
  ^^^^^^^^^^^^^^^
SyntaxError: Named export 'simpleEstimator' not found. The requested module 'graphql-query-complexity' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'graphql-query-complexity';

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:142:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Ideally don't publish CJS at all, to avoid the [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard).

Please make sure that the modules can all be deep imported without having to go through the index; that way we can avoid the JavaScript runtime parsing and loading into memory stuff our program doesn't use. E.g:

```js
import createComplexityRule from 'graphql-query-complexity/createComplexityRule.mjs';
import simpleEstimator from 'graphql-query-complexity/simpleEstimator.mjs';
```

**Comment by ivome** [comment]
Thanks for bringing this up @jaydenseric . Given that the ESM module support isn't working properly at the moment we have to assume that all codebases use this in a CommonJS context. So dropping CommonJS support could be a big change for a lot of projects. 

The hybrid module support has quite a few quirks (you mentioned some of them), and TypeScript has just excluded proper ESM support from the next release microsoft/TypeScript#46452 which would have made this a lot easier.

But I think I got a solution with the implemented changes. I changed the build processes to export both a CommonJS and ESM version of the bundle + tests that run on both exported code versions, which enables people to gradually update their codebases. This should fix this issue here. 
You can also load the files directly, but if we drop support for CommonJS in a future release, the paths will likely change.

**Comment by ivome** [comment]
This should work now with v0.11
